### ISSUE TITLE
Arduino Syntax doesn't stay focus

### ISSUE THREAD

**Issue by mnett0** [szechyjs/language-arduino#20]
Hello,
The plugin works perfectly (or almost) the concern is that I am obliged to select the Arduino syntax at each launch of Atom without which it selects me the C++ syntax all the time, do you have a solution for this? 

Atom v1.23.1

**Comment by szechyjs** [comment]
Do your files have a `ino` or `pde` extension?

**Comment by mnett0** [comment]
Yes
 I'm using platformIO maybe that's the problem? 

![screenshoot](https://user-images.githubusercontent.com/35499751/45053734-2efbd980-b08b-11e8-90b1-404ed0416966.png)

**Comment by szechyjs** [comment]
My guess would be that platformIO causes the conflict.

**Comment by mnett0** [comment]
Yes, when I disable platformIO there are no more problems. 
I have just found the solution: https://community.platformio.org/t/platformio-atom-possibly-changing-grammar-for-pde-files/283/2
