### ISSUE TITLE
[Feature Request] Compile sketches directly from the editor

### ISSUE THREAD

**Issue by bojidar-bg** [szechyjs/language-arduino#4]
It will be very nice if it is possible to compile (and upload) the sketches directly from Atom.

Just for reference:
http://macbury.ninja/2014/8/compiling-sketches-for-arduino-in-linux-console

**Comment by Eriatolc** [comment]
I would say even more: have also the downloading of a sketch to the board feature. If this plugin could do the same as the [Sublime Text's plugin Stino](https://github.com/Robot-Will/Stino), it would be perfect!

**Comment by jonatasleon** [comment]
arduino-language just covers the grammar and some snippets. For features like build and upload look [this](https://discuss.atom.io/t/programming-arduino/15661/6)

**Comment by Peteous** [comment]
While I agree with @bojidar-bg that it would be really nice to have an integrated, all-in-one arduino solution package for Atom, you could use [this linked package](https://github.com/Sorunome/arduino-upload) to upload your arduino code, and this current package for language support. It's not elegant or ideal, but it works.

**Comment by qub1750ul** [comment]
Why not use the platformio plugin for atom?
It is literally a **integrated, fully faetured, all-in-one arduino ( and tons of other platforms ) solution package**, it has full native integrated support for snippets, code completion, on-the-fly code linting, upload, serial connection, library manager, multi-board per-project settings for the arduino stuff and even more.

http://docs.platformio.org/en/stable/ide/atom.html#installation

**Comment by Xatrix97** [comment]
There is an other project that support this beautifully
[https://atom.io/packages/arduino-upload](url)

**Comment by bojidar-bg** [comment]
Ok, guess this is not something the arduino-language package is supposed to do (as it is just a grammar package), and there are many other packages for it out there, so I guess I will close it now 😃
